# main workflow file
name: Build and Push to Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

# Job to build the React Js files using NPM
  codebuild:
    name: Build Code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --production
 #  - run: npm test

# Build the Docker image using files generated in prev step
  dockerbuild:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: codebuild
