# main workflow file
name: Build and Push to Docker

# Trigger this workflow on commit to master
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Job to build the React Js files using NPM
  codebuild:
    name: Build Code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install --production
      - run: npm run build --production
  #  - run: npm test

  # Build the Docker image using files generated in prev step
  dockerbuild:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: codebuild
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #  Login to Docker Hub
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # Build Docker Image using Prebuild Image
      - name: Build Docker Image
        run: docker build -t manjoy.in .

      # Push to Docker Hub
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/manjoy.in
